name: Scrape Stock Info

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at midnight on the 1st day of each month
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python bse500_scrape.py  # Replace with the actual filename of your Python script

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add bse500.csv
        git commit -m "Updated the CSV with data as of $(date +'%Y-%m-%d')"
        git push
